/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AllowlistRegistry__factory } from "./AllowlistRegistry__factory";
export { RestrictedToken__factory } from "./RestrictedToken__factory";
